name: Address CRI Stub - Secure Pipeline build, push & Ship
on:
  push:
    branches:
      - main
    paths:
      - di-ipv-credential-issuer-stub/deploy/address/*
      - di-ipv-credential-issuer-stub/gradle/**
      - di-ipv-credential-issuer-stub/src/**
      - di-ipv-credential-issuer-stub/*
      - .github/workflows/cri-address-stub.yml
  workflow_dispatch:

jobs:
  dockerBuildAndPush:
    uses: ./.github/workflows/cri-stub-test-build-and-push.yml
    permissions:
      id-token: write
      contents: read
      packages: read
    with:
      WORKING_DIRECTORY: ./di-ipv-credential-issuer-stub/deploy/address
    secrets:
      ARTIFACT_BUCKET_NAME: ${{ secrets.CRI_ADDRESS_ARTIFACT_BUCKET_NAME }}
      CONTAINER_SIGN_KMS_KEY: ${{ secrets.CONTAINER_SIGN_KMS_KEY }}
      DYNATRACE_PAAS_TOKEN: ${{ secrets.DYNATRACE_PAAS_TOKEN }}
      ECR_REPOSITORY: ${{ secrets.CRI_ADDRESS_ECR_REPOSITORY }}
      GH_ACTIONS_ROLE_ARN: ${{ secrets.CRI_ADDRESS_GH_ACTIONS_ROLE_ARN }}
