name: EVCS Stub Build Build & Push
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - di-ipv-evcs-stub/**
      - .github/workflows/evcs-stub.yml

jobs:
  test:
    uses: ./.github/workflows/test-and-build.yml
    permissions:
      packages: read
  buildAndPush:
    needs: test
    name: Build and push
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@v2

      - name: Set up esbuild
        run: curl -fsSL https://esbuild.github.io/dl/latest | sh

      - name: add esbuild to path
        run: echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH

      - name: check esbuild works
        run: esbuild --version

      - name: SAM Validate
        working-directory: ./di-ipv-evcs-stub/deploy
        run: sam validate --region ${{ env.AWS_REGION }}

      - name: npm install
        working-directory: ./di-ipv-evcs-stub/lambdas
        run: npm ci

      - name: npm test
        working-directory: ./di-ipv-evcs-stub/lambdas
        run: npm run test

      - name: SAM build
        working-directory: ./di-ipv-evcs-stub/deploy
        run: sam build

      - name: Deploy to IPV Stubs accounts
        uses: ./.github/actions/deploy-evcs-stub
        with:
          role-to-assume: ${{ secrets.EVCS_STUB_BUILD_GH_ROLE }}
          artifact-bucket-name: ${{ secrets.EVCS_STUB_BUILD_S3_BUCKET }}
          signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME }}

      - name: Deploy to Reuse Stubs dev account
        uses: ./.github/actions/deploy-evcs-stub
        with:
          role-to-assume: ${{ secrets.REUSE_EVCS_STUB_DEV_GH_ROLE }}
          artifact-bucket-name: ${{ secrets.REUSE_EVCS_STUB_DEV_S3_BUCKET }}
          signing-profile-name: ${{ secrets.REUSE_DEV_SIGNING_PROFILE_NAME }}

      - name: Deploy to Reuse Stubs build account
        uses: ./.github/actions/deploy-evcs-stub
        with:
          role-to-assume: ${{ secrets.REUSE_EVCS_STUB_BUILD_GH_ROLE }}
          artifact-bucket-name: ${{ secrets.REUSE_EVCS_STUB_BUILD_S3_BUCKET }}
          signing-profile-name: ${{ secrets.REUSE_BUILD_SIGNING_PROFILE_NAME }}
