name: SIS Stub Build Build & Push
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - di-ipv-sis-stub/**
      - .github/workflows/sis-stub.yml

jobs:
  buildAndPush:
    name: Build and push
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          role-to-assume: ${{ secrets.SIS_STUB_BUILD_GH_ROLE }}
          aws-region: eu-west-2

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@v2

      - name: Set up esbuild
        run: curl -fsSL https://esbuild.github.io/dl/latest | sh

      - name: add esbuild to path
        run: echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH

      - name: check esbuild works
        run: esbuild --version

      - name: SAM Validate
        working-directory: ./di-ipv-sis-stub/deploy
        run: sam validate --region ${{ env.AWS_REGION }}

      - name: npm install
        working-directory: ./di-ipv-sis-stub/lambdas
        run: npm ci

      - name: check for tsc compile errors
        working-directory: ./di-ipv-sis-stub/lambdas
        run: npm run build

      - name: npm test
        working-directory: ./di-ipv-sis-stub/lambdas
        run: npm run test

      - name: SAM build
        working-directory: ./di-ipv-sis-stub/deploy
        run: sam build

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@v3.9
        with:
          artifact-bucket-name: ${{ secrets.SIS_STUB_BUILD_S3_BUCKET }}
          signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME }}
          working-directory: ./di-ipv-sis-stub/deploy
          template-file: .aws-sam/build/template.yaml
